ALTER TABLE `cv_propiedades`
	ADD COLUMN `PROPIEDADES_LATITUD` FLOAT NULL DEFAULT NULL AFTER `PROPIEDADES_VIDEO`,
	ADD COLUMN `PROPIEDADES_LONGITUD` FLOAT NULL DEFAULT NULL AFTER `PROPIEDADES_LATITUD`;
